---
- name: Install utilities
  apt:
    name:
      - openssh-server
      - fail2ban
      - apt-listchanges
      - unattended-upgrades
      - etckeeper
    state: present
  register: apt_result
  retries: 3
  until: apt_result is succeeded

- name: Enable services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - ssh
    - fail2ban
    - etckeeper.timer

- name: Disable root and password SSH login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^#?{{ item.option }}
    line: "{{ item.option }} {{ item.value }}"
    state: present
  loop:
    - option: PermitRootLogin
      value: "no"
    - option: PasswordAuthentication
      value: "no"
  notify: Restart SSH

- name: Configure timezone
  timezone:
    name: "{{ base_timezone }}"
...
