---
- name: Install OpenSSH server
  apt:
    name: openssh-server
    state: present
  register: apt_result
  retries: 3
  until: apt_result is succeeded

- name: Enable OpenSSH server
  systemd:
    name: ssh
    state: started
    enabled: true

- name: Disable root and password SSH login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^#?{{ item.option }}
    line: "{{ item.option }} {{ item.value }}"
    state: present
  loop:
    - option: PermitRootLogin
      value: "no"
    - option: PasswordAuthentication
      value: "no"
  notify: Restart SSH
...
